// Pure rendering + naming logic. No docker, no filesystem — so it is testable
// without a daemon (see test/compose.test.ts).

export const REGISTRY = "ghcr.io/hsb3/opencode"

/** Provider keys forwarded from the caller's environment into an instance. */
export const PROVIDER_KEYS = [
  "ANTHROPIC_API_KEY",
  "OPENAI_API_KEY",
  "GOOGLE_GENERATIVE_AI_API_KEY",
  "OPENROUTER_API_KEY",
] as const

export const NAME_RE = /^[a-z0-9][a-z0-9-]{0,30}$/

export function projectName(name: string) {
  return `ocsbx-${name}`
}

/**
 * Deterministic starting point for port probing, so the same instance name
 * lands on the same pair across machines when the ports happen to be free.
 * FNV-1a over the name; the caller still probes upward for an actually free pair.
 */
export function basePort(name: string, lo = 4300, hi = 4899) {
  let h = 2166136261
  for (const c of name) {
    h ^= c.charCodeAt(0)
    h = Math.imul(h, 16777619) >>> 0
  }
  const span = Math.floor((hi - lo) / 2)
  return lo + (h % span) * 2
}

export type Instance = {
  name: string
  mcpPort: number
  webPort: number
  apiPort?: number
  tag: string
  web: boolean
}

export function renderCompose(apiPort?: number): string {
  // Images only — a consumer never builds. Service name `opencode` is load-bearing:
  // the web image's baked nginx.conf proxies to http://opencode:4097.
  return `# Generated by opencode-sandbox. Edits are overwritten on the next create.
services:
  opencode:
    image: ${REGISTRY}/backend:\${OC_TAG}
    env_file: [.env]
    volumes:
      - workspace:/workspace
      - data:/root/.local/share/opencode
      - cache:/root/.cache/opencode
      - state:/root/.local/state/opencode
      - ./config:/root/.config/opencode
    working_dir: /workspace
${apiPort ? `    ports: ["127.0.0.1:\${API_PORT}:4097"]\n` : ""}    environment:
      # /root, not /workspace — otherwise .npm/.claude/etc. pollute the repo.
      HOME: /root
      OPENCODE_DISABLE_EMBEDDED_WEB_UI: "1"
      OPENCODE_DISABLE_CHANNEL_DB: "1"
      OPENCODE_DISABLE_AUTOUPDATE: "1"
      XDG_DATA_HOME: /root/.local/share
      XDG_CONFIG_HOME: /root/.config
      XDG_CACHE_HOME: /root/.cache
      XDG_STATE_HOME: /root/.local/state
    restart: unless-stopped

  # No inbound auth — see README's security note. Host bind stays on 127.0.0.1.
  mcp:
    image: ${REGISTRY}/mcp:\${OC_TAG}
    entrypoint: ["supergateway"]
    command: ["--stdio", "opencode-mcp", "--outputTransport", "streamableHttp", "--port", "8000"]
    environment:
      OPENCODE_BASE_URL: http://opencode:4097
    ports: ["127.0.0.1:\${MCP_PORT}:8000"]
    depends_on: [opencode]
    restart: unless-stopped

  web:
    image: ${REGISTRY}/web:\${OC_TAG}
    profiles: [web]
    ports: ["127.0.0.1:\${WEB_PORT}:80"]
    depends_on: [opencode]
    restart: unless-stopped

volumes:
  workspace:
  data:
  cache:
  state:
`
}

export function renderEnv(inst: Instance, env: Record<string, string | undefined>): string {
  const lines = [
    `OC_TAG=${inst.tag}`,
    `MCP_PORT=${inst.mcpPort}`,
    `WEB_PORT=${inst.webPort}`,
    "OPENCODE_DISABLE_AUTOUPDATE=1",
  ]
  if (inst.apiPort) lines.push(`API_PORT=${inst.apiPort}`)
  for (const k of PROVIDER_KEYS) if (env[k]) lines.push(`${k}=${env[k]}`)
  return lines.join("\n") + "\n"
}

export function mcpUrl(inst: Instance) {
  return `http://127.0.0.1:${inst.mcpPort}/mcp`
}

export function registerLine(inst: Instance) {
  return `claude mcp add --transport http ${inst.name} ${mcpUrl(inst)}`
}
